insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,COMPANY,POLICY_PRICE)values(1,'JIVAN VIMA SURKSHA','LIC',11000);
insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,COMPANY,POLICY_PRICE)values(2,'HDFC LIFE','HDFC',7000);
insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,COMPANY,POLICY_PRICE)values(3,'TATA AIG MEDICARE','TATA',6000);
